// #include "testasset.hpp"

// // Symbols generated by .incbin
// extern "C"
// {
//     extern const unsigned char amogus_txt_start[];
//     extern const unsigned char amogus_txt_end[];
// }

// __asm__(
//     ".global amogus_txt_start\n"
//     "amogus_txt_start:\n"
//     ".incbin \"src/amogus.txt\"\n"
//     ".global amogus_txt_end\n"
//     "amogus_txt_end:\n");

// size_t myfile_size()
// {
//     return (size_t)(amogus_txt_end - amogus_txt_start);
// }

// const char *myfile_data()
// {
//     return (const char *)amogus_txt_start;
// }
